Q.3. Perform the following operations on an array of mobile phones prices 6999, 7500,
11999, 27899, 14999, 9999.
1. Create a 1d-array of mobile phones prices
2. Convert this array to float type
3. Append a new mobile having price of 13999 Rs. to this array
4. Reverse this array of mobile phones prices
5. Apply GST of 18% on mobile phones prices and update this array.
6. Sort the array in descending order of price
7. What is the average mobile phone price
8. What is the difference b/w maximum and minimum price

In [1]:
import numpy as np

In [3]:
mobile_price=np.array([6999,7500,11999,27899,14999,9999])
mobile_price

array([ 6999,  7500, 11999, 27899, 14999,  9999])

In [4]:
mobile_price=mobile_price.astype(float)
mobile_price

array([ 6999.,  7500., 11999., 27899., 14999.,  9999.])

In [7]:
mobile_price=np.append(mobile_price,13999)
mobile_price

array([ 6999.,  7500., 11999., 27899., 14999.,  9999., 13999.])

In [9]:
mobile_price = mobile_price[::-1]
mobile_price

array([13999.,  9999., 14999., 27899., 11999.,  7500.,  6999.])

In [10]:
mobile_price=mobile_price * 1.18
mobile_price

array([16518.82, 11798.82, 17698.82, 32920.82, 14158.82,  8850.  ,
        8258.82])

In [11]:
mobile_price=np.sort(mobile_price)[::-1]
mobile_price

array([32920.82, 17698.82, 16518.82, 14158.82, 11798.82,  8850.  ,
        8258.82])

In [12]:
avg_price = np.mean(mobile_price)
avg_price

np.float64(15743.560000000001)

In [14]:
price_diff = np.max(mobile_price) - np.min(mobile_price)
price_diff

np.float64(24662.0)