Q.10. Create a 2x2 matrix A and a 2x2 matrix B. Perform matrix multiplication using np.dot() or
the @ operator.

In [1]:
import numpy as np

In [2]:
A = np.array([[1, 2], [3, 4]])
A

array([[1, 2],
       [3, 4]])

In [3]:
B = np.array([[5, 6], [7, 8]])
B

array([[5, 6],
       [7, 8]])

In [4]:
result = A @ B
result

array([[19, 22],
       [43, 50]])

In [5]:
result = np.dot(A,B)
result

array([[19, 22],
       [43, 50]])