Q.11. Find the transpose of matrix A and matrix B.

In [1]:
import numpy as np

In [2]:
A = np.array([[7,4], [3, 4]])
A

array([[7, 4],
       [3, 4]])

In [3]:
B = np.array([[2, 6], [7, 9]])
B

array([[2, 6],
       [7, 9]])

In [4]:
transpose_a = np.transpose(A)
transpose_a

array([[7, 3],
       [4, 4]])

In [5]:
transpose_b = np.transpose(B)
transpose_b

array([[2, 7],
       [6, 9]])