Q.12. Create a 3x3 array and a 1D array with 3 elements. Add the 1D array to the 2D array.
Explain how broadcasting works in this operation.

In [1]:
import numpy as np

In [3]:
matrix1 = np.arange(9).reshape(3,3)
matrix1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
arr_1d = np.array([10, 20, 30])
arr_1d

array([10, 20, 30])

In [6]:
matrix1 + arr_1d

array([[10, 21, 32],
       [13, 24, 35],
       [16, 27, 38]])