Q.8. Create two arrays of shape (2, 3): arr1 and arr2. Perform element-wise addition,
subtraction, multiplication, and division on them.

In [1]:
import numpy as np

In [3]:
arr1 = np.array([[10, 20, 30], [40, 50, 60]])
arr1

array([[10, 20, 30],
       [40, 50, 60]])

In [4]:
arr2 = np.array([[2, 4, 5], [10, 2, 3]])
arr2

array([[ 2,  4,  5],
       [10,  2,  3]])

In [5]:
arr3 = arr1 + arr2
arr3

array([[12, 24, 35],
       [50, 52, 63]])

In [7]:
arr3 = arr1 - arr2
arr3

array([[ 8, 16, 25],
       [30, 48, 57]])

In [8]:
arr3 = arr1 * arr2
arr3

array([[ 20,  80, 150],
       [400, 100, 180]])

In [9]:
arr3 = arr1 / arr2
arr3

array([[ 5.,  5.,  6.],
       [ 4., 25., 20.]])